# Generated by Django 3.0 on 2019-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('X', models.DecimalField(decimal_places=20, help_text='Longitude', max_digits=50)),
                ('Y', models.DecimalField(decimal_places=20, help_text='Latitude', max_digits=50)),
                ('unique_squirrel_id', models.CharField(help_text='unique squirrel id', max_length=100, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=10)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', ''), ('Unknown', '?')], help_text='Age', max_length=50)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('', '')], help_text='Primary Fur Color', max_length=20)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], help_text='Location', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=100)),
                ('Running', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Running', max_length=10)),
                ('Chasing', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Chasing', max_length=10)),
                ('Climbing', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Climbing', max_length=10)),
                ('Eating', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Eating', max_length=10)),
                ('Foraging', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Foraging', max_length=10)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=100)),
                ('Kuks', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Kuks', max_length=10)),
                ('Quaas', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Quaas', max_length=10)),
                ('Moans', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Moans', max_length=10)),
                ('Tail_Flags', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail Flags', max_length=10)),
                ('Tail_Twitches', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail Twitches', max_length=10)),
                ('Approaches', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Approaches', max_length=10)),
                ('Indifferent', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Indifferent', max_length=10)),
                ('Runs_From', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Runs From', max_length=10)),
            ],
        ),
    ]
